# This is a basic workflow that is manually triggered

name: Manual workflow

on:
    push:
      branches: 
        - master
      paths: 
        - iac/terraform/**
        - .guthub/workflows/**
    pull_request:
      branches: 
        - master
      paths: 
        - iac/terraform/**
env:
  # credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the terraform state. 
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF }}
  AWS_REGION: eu-north-1

jobs:
  terraform:
    name: "Apply terraform code changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./iac/terraform
    steps:
    - name: Checkout source code 
      uses: actions/checkout@v4


      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -parallelism=1 planfile
